# Generated by Django 4.0.5 on 2022-07-22 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('result', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('Qques', models.TextField(max_length=200, null=True)),
                ('Qoption1', models.TextField(max_length=200, null=True)),
                ('Qoption2', models.TextField(max_length=200, null=True)),
                ('Qoption3', models.TextField(max_length=200, null=True)),
                ('Qoption4', models.TextField(max_length=200, null=True)),
                ('QAnswer', models.TextField(max_length=200, null=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('candidate_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
