# Generated by Django 3.1.5 on 2022-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20220803_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.FileField(upload_to='media')),
            ],
        ),
    ]
