# Generated by Django 3.1.5 on 2022-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_audiomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='op',
            field=models.FileField(upload_to='file'),
        ),
    ]
