# Generated by Django 3.1.5 on 2022-08-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20220812_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='op',
            field=models.FileField(upload_to='media'),
        ),
    ]
